application: tessernote
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /static
  static_dir: github.com/oschmid/tessernote/static
  secure: always

- url: /.*
  script: _go_app
  secure: always
