application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /scripts
  static_dir: static/scripts

- url: /.*
  script: _go_app
